# Generated by Django 5.2.7 on 2025-10-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Все пользователи',
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Название группы')),
                ('discription', models.TextField(verbose_name='Описание группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userslist')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Все группы',
            },
        ),
    ]
