# Generated by Django 5.2.7 on 2025-10-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupuser',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Все группы'},
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='users_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userslist', verbose_name='Список участников:'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Информация в посте:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userslist', verbose_name='ID автора:')),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.groupuser', verbose_name='ID группы:')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Все посты',
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userslist', verbose_name='ID автора:')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='ID поста:')),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userslist', verbose_name='ID автора:')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='ID поста:')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Все комментарии',
            },
        ),
    ]
