# Generated by Django 5.2.7 on 2025-10-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_groupuser_options_alter_groupuser_users_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likepost',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Все лайки'},
        ),
    ]
