# Generated by Django 5.2.7 on 2025-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_likepost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupuser',
            name='users_list',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='users_list',
            field=models.ManyToManyField(blank=True, to='main.userslist', verbose_name='Участники группы'),
        ),
    ]
